### ISSUE TITLE
error in download_queue functie maar download werkt wel.

### ISSUE THREAD

**Issue by Rafaelorr** [Rafaelorr/youtube_video_downloader#2]
als de lijst klaar is in de download_queue is krijgt je deze error.
Traceback (most recent call last):
  File "/home/rafael/Documenten/gebackupt/coderdojo/python_repos/youtube_video_downloader/main.py", line 48, in <module>
    download_queue(download_queue_list=download_queue_list)
  File "/home/rafael/Documenten/gebackupt/coderdojo/python_repos/youtube_video_downloader/main.py", line 36, in download_queue
    file_extension:str = download_queue_list[i+2]
IndexError: list index out of range

**Comment by Rafaelorr** [comment]
fixed door een try blok toe te voegen.
